# Matemática para Ciencia de los Datos
# Trabajo Práctico 2

Profesor: Juan Luis Crespo Mariño, basado en trabajo previo de Luis Alexánder Calvo Valverde

Instituto Tecnológico de Costa Rica,

Programa Ciencia de Datos

---

Fecha de entrega: 27 de febrero, hora límite las 6:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo jupyter ( .IPYNB ).

Estudiante(s):
1. **Antony Medina**


---

**Pregunta 1**

Considerando que la transpuesta de una matriz es el resultado de cambiar las filas a columnas. Sea una matriz $A\in\mathbb{R}^{m\times n}$, su transpuesta se escribe como $A^{T}\in\mathbb{R}^{n\times m}$ y sus entradas están dadas por:

\begin{equation}
\left(A^{T}\right)_{i,j}=A_{j,i}.
\end{equation}

Proponga Usted dos matrices, $A\in\mathbb{R}^{4\times 3}$ y $B\in\mathbb{R}^{3\times 4}$ (no las busque en Internet, trate de proponer los valores por si mismo), y utilizando numpy muestre que las siguientes propiedades se cumplen con sus matrices propuestas.

**Note** que ni A ni B son cuadradas, y no tienen las mismas dimensiones.


**1.1 (15 puntos)**

- $\left(A^{T}\right)^{T}=A$


In [1]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
###############################################################################

A = np.array ([[1, 2, 3],
              [2, 4, 6],
              [4, 8, 12],
              [8, 16, 24]
             ])

At = np.transpose(A)

Att = np.transpose(At)

print(f"Matriz A: \n{A}")
print("--------------")
print(f"Matriz transpuesta de A:\n {At}")
print("--------------")
print(f"Matriz transpuesta de transpuesta de A: \n {Att}")
print("--------------")
#print(f"(At)t == A => \n { np.equal(A, Att)}")
print(f"(Aᵗ)ᵗ == A => { np.array_equal(A, Att)}")

Matriz A: 
[[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]
 [ 8 16 24]]
--------------
Matriz transpuesta de A:
 [[ 1  2  4  8]
 [ 2  4  8 16]
 [ 3  6 12 24]]
--------------
Matriz transpuesta de transpuesta de A: 
 [[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]
 [ 8 16 24]]
--------------
(Aᵗ)ᵗ == A => True


**1.2 (15 puntos)**

- $\left(AB\right)^{T}=B^{T}A^{T}$


In [2]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
###############################################################################

A = np.array ([[1, 2, 3],
              [2, 4, 6],
              [4, 8, 12],
              [8, 16, 24]
             ])

B = np.array ([[1, 2, 3, 4],
              [3, 6, 9, 12],
              [9, 18, 27, 36],
             ])

AB = np.matmul(A, B)
ABt = np.transpose(AB)

print(ABt)
print("--------------")

Bt = np.transpose(B)
At = np.transpose(A)

BtPlusAt = np.matmul(Bt, At)

print (BtPlusAt)
print("--------------")

print(f"(AB)ᵗ == (Bᵗ)(Aᵗ) => {np.array_equal(ABt, BtPlusAt)}")

[[  34   68  136  272]
 [  68  136  272  544]
 [ 102  204  408  816]
 [ 136  272  544 1088]]
--------------
[[  34   68  136  272]
 [  68  136  272  544]
 [ 102  204  408  816]
 [ 136  272  544 1088]]
--------------
(AB)ᵗ == (Bᵗ)(Aᵗ) => True


**1.3 (15 puntos)**

Para este ejercicio, **proponga dos matrices de igual dimensionalidad**


- $\left(A+B\right)^{T}=A^{T}+B^{T}$.


In [3]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
###############################################################################

A = np.array ([[1, 2, 3],
              [2, 4, 6],
              [4, 8, 12],
             ])

B = np.array ([[1, 2, 3],
              [3, 6, 9],
              [9, 18, 27],
             ])

APlusB = np.add(A, B)
APlusB_t = np.transpose(APlusB)

print(APlusB_t)
print("--------------")

At = np.transpose(A)
Bt = np.transpose(B)

AtPlusBt = np.add(At, Bt)

print(AtPlusBt)
print("--------------")

print(f"(A+B)ᵗ == Aᵗ + Bᵗ => {np.array_equal(APlusB_t, AtPlusBt)}")


[[ 2  5 13]
 [ 4 10 26]
 [ 6 15 39]]
--------------
[[ 2  5 13]
 [ 4 10 26]
 [ 6 15 39]]
--------------
(A+B)ᵗ == Aᵗ + Bᵗ => True


---

**Pregunta 2**


Un conjunto de vectores $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \in\mathbb{R}^{m}$ se dice que es linealmente independiente, si ningún vector de tal conjunto puede ser representado como una combinación lineal del resto de vectores. De lo contrario, si uno de los vectores en tal conjunto puede ser representado como una combinación lineal del resto de vectores, entonces los vectores son linealmente dependientes, lo que se expresa como:

\begin{equation}
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
\end{equation}

para cualquier conjunto de valores escalares $\alpha_{1},\ldots,\alpha_{n-1}\in\mathbb{R}$ se dice que el vector $\vec{x}_{j}\in\mathbb{R}^{m}$ es linealmente dependiente de los vectores $\vec{x}_{i}$.


**2.1 (15 puntos)**

Proponga una matriz $A\in\mathbb{R}^{4\times 3}$, cuyos vectores columnas sean linealmente independientes, calcule su rango para mostrar que es de rango $3$ (puede utilizar matrix_rank).


In [4]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from numpy.linalg import matrix_rank
###############################################################################

A = np.array ([[3, 17, 7],
              [3, 4, 30],
              [7, 8, 12],
              [8, 9, 65]
             ])

print(f"Rango: {matrix_rank(A)}")

Rango: 3


**2.2 (15 puntos)**

Ahora haga los cambios necesarios a su matriz de manera que pase a rango $2$.

In [5]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from numpy.linalg import matrix_rank
###############################################################################

A = np.array ([[3, 17, 7],
              [12, 68, 28],
              [6, 34, 14],
              [8, 9, 66]
             ])

print(f"Rango: {matrix_rank(A)}")

Rango: 2


---

**Pregunta 3 (25 puntos)**

Utilizando el archivo "Dataset_usar.csv", haga:
- Cargue el archivo.
- Utilizando el modelo $Ax=b$
    - Conforme la matriz $A$ con las primeras 8 columnas.
    - Conforme el vector $b$ con la última columna de la derecha.
    - Calcule el vector de pesos ($x$), del tipo $A^{-1}b=x$
    - Calcule un b_estimado con $A$ e $x$
    - Calcule la norma 2 de la diferencia entre b y b_estimado.
    - Grafique b y b_estimado.



In [ ]:
###############################################################################
import math
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from numpy.linalg import matrix_rank
import pandas as pd
from numpy.linalg import inv
from numpy.linalg import pinv

###############################################################################

pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 9)
pd.set_option('display.width', 1000)

# uploaded = files.upload() # This will prompt you to select a file

separador = "-"*30
archivo = ""

# carga el archivo en pandas
dataFrame = pd.read_csv(archivo, header = 0, delimiter=';')

# guarda el nombre de las columnas en una lista
colNames = dataFrame.columns


# muestra los primeros elementos del dataFrame
# print(separador)
# print("Datos en dataFrame:")
# print(dataFrame.head() )

# Convertir de pandas a numpy
datos = pd.DataFrame(dataFrame).to_numpy().astype(np.float64)

A = datos[:, :8]
b = datos[:, 8]

A_frame = pd.DataFrame(A, columns=colNames[:8])
b_frame = pd.DataFrame(b, columns=[colNames[8]])

# print(separador)
# print(A_frame)
# print(separador)
# print(b_frame)

#print(b)

try:
  AInv = inv(A)
  print("La matriz A es invertible")
except:
  print("La matriz A NO es invertible")

Apinv = pinv(A)
pseudo_x = np.matmul(Apinv, b)

print(separador)
b_estimado = np.matmul(A,pseudo_x)
#print(f"b_estimado = \n {b_estimado}")

diferenciaB = b - b_estimado
normaDifB = np.linalg.norm(diferenciaB, 2)

print(f"norma 2 del error (b - b_estimado) = \n {normaDifB}")

# Para verificar cuales columnas son dependientes
# for i in range(A.shape[1]):
#     A_temp = np.delete(A, i, axis=1)
#     print(f"Quitando columna {i}, rango:", matrix_rank(A_temp))

plt.figure(figsize=(8,5))
plt.plot(b, label="b")
plt.plot(b_estimado, label="b_estimado")
plt.title("Comparación: b vs b_estimado")
plt.xlabel("Índice")
plt.ylabel("Valor")
plt.legend()
plt.grid(True)
plt.show()


ModuleNotFoundError: No module named 'google'